name: Local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: jwtToken
    value: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZWphcyIsImlhdCI6MTc4NTY5NzQ0MiwiZXhwIjoxNzg1NzgzODQyfQ.KiRWl8OLyKWpPwYb5qaPQko9ouJfMTB20mWaf-usaVM4iAJ9y1_nKLlsXzi-XZ7sYmSJUUxjYaexjflrSLykOA
